'use client';

import { useState } from 'react';
import { Providers } from '@/lib/providers';
import '../styles/globals.css';
import Sidebar from '../components/admin/Sidebar';
import Navbar from '../components/admin/Navbar';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

function RootLayout({ children }: { children: React.ReactNode }) {
  const [sideActive, setSideActive] = useState(true);
  const sideHandle = () => {
    setSideActive(!sideActive);
  };
  return (
    <Providers>
      <html lang="en">
        <body>
          <div className="flex">
            {/* side bar */}
            <Sidebar sideHandle={sideHandle} sideActive={sideActive} />
            {/* side bar end */}

            <div className={`${sideActive ? 'md:w-10/12' : ''} w-full `}>
              {/* Nav bar */}
              <Navbar sideHandle={sideHandle} />
              {/* nav bar end */}
              <div className="h-screen">{children}</div>
            </div>
          </div>
        </body>
      </html>
    </Providers>
  );
}
export default RootLayout;
